# Generated by Django 2.2.1 on 2019-05-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190512_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='thumb',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='document',
            field=models.FileField(blank=True, upload_to='profile_image/'),
        ),
    ]
