# Generated by Django 2.2.1 on 2019-05-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190513_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='document',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='thumb',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
