# Generated by Django 2.2.1 on 2019-05-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190514_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_image'),
        ),
    ]
